GAMES = [
    {
        "name": "Zelda 64: Recompiled",
        "game_title": "The Legend of Zelda: Majora's Mask",
        "console": "Nintendo 64",
        "repo": "Zelda64Recomp/Zelda64Recomp",
        "folder": "Zelda64Recompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/Zelda64Recomp/Zelda64Recomp/refs/heads/dev/icons/512.png",
    },
    {
        "name": "Goemon 64: Recompiled",
        "game_title": "Mystical Ninja Starring Goemon",
        "console": "Nintendo 64",
        "repo": "klorfmorf/Goemon64Recomp",
        "folder": "Goemon64Recompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/klorfmorf/Goemon64Recomp/refs/heads/dev/icons/512.png",
    },
    {
        "name": "Mario Kart 64: Recompiled",
        "game_title": "Mario Kart 64",
        "console": "Nintendo 64",
        "repo": "sonicdcer/MarioKart64Recomp",
        "folder": "MarioKart64Recompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/sonicdcer/MarioKart64Recomp/refs/heads/main/icons/512.png",
    },
    {
        "name": "Duke Nukem: Zero Hour Recompiled",
        "game_title": "Duke Nukem: Zero Hour",
        "console": "Nintendo 64",
        "repo": "sonicdcer/DNZHRecomp",
        "folder": "DNZHRecompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/sonicdcer/DNZHRecomp/refs/heads/main/icons/512.png",
    },
    {
        "name": "Star Fox 64: Recompiled",
        "game_title": "Star Fox 64",
        "console": "Nintendo 64",
        "repo": "sonicdcer/Starfox64Recomp",
        "folder": "Starfox64Recompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/sonicdcer/Starfox64Recomp/refs/heads/main/icons/512.png",
    },
    {
        "name": "Banjo-Kazooie: Recompiled",
        "game_title": "Banjo-Kazooie",
        "console": "Nintendo 64",
        "repo": "BanjoRecomp/BanjoRecomp",
        "folder": "BanjoRecompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/BanjoRecomp/BanjoRecomp/refs/heads/main/icons/app.png",
    },
    {
        "name": "Bomberman 64: Recompiled",
        "game_title": "Bomberman 64",
        "console": "Nintendo 64",
        "repo": "RevoSucks/BM64Recomp",
        "folder": "BM64Recompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/RevoSucks/BM64Recomp/refs/heads/master/icons/512.png",
    },
    {
        "name": "Space Station Silicon Valley: Recompiled",
        "game_title": "Space Station Silicon Valley",
        "console": "Nintendo 64",
        "repo": "Cellenseres/SSSV_Recomp",
        "folder": "SSSVRecompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/Cellenseres/SSSV_Recomp/refs/heads/main/icons/512.png",
    },
    {
        "name": "Ship of Harkinian",
        "game_title": "The Legend of Zelda: Ocarina of Time",
        "console": "Nintendo 64",
        "repo": "harbourmasters/shipwright",
        "folder": "ShipOfHarkinian",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "SpaghettiKart",
        "game_title": "Mario Kart 64",
        "console": "Nintendo 64",
        "repo": "harbourmasters/spaghettikart",
        "folder": "SpaghettiKart",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "2 Ship 2 Harkinian",
        "game_title": "The Legend of Zelda: Majora's Mask",
        "console": "Nintendo 64",
        "repo": "harbourmasters/2ship2harkinian",
        "folder": "2Ship2Harkinian",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "Ghost Ship",
        "game_title": "Super Mario 64",
        "console": "Nintendo 64",
        "repo": "harbourmasters/ghostship",
        "folder": "GhostShip",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/HarbourMasters/Ghostship/refs/heads/develop/nx-logo.jpg",
    },
    {
        "name": "Perfect Dark",
        "game_title": "Perfect Dark",
        "console": "Nintendo 64",
        "repo": "fgsfdsfgs/perfect_dark",
        "folder": "PerfectDark",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "SM64 Co-op Deluxe",
        "game_title": "Super Mario 64",
        "console": "Nintendo 64",
        "repo": "coop-deluxe/sm64coopdx",
        "folder": "SM64CoopDX",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "Zelda: A Link to the Past",
        "game_title": "The Legend of Zelda: A Link to the Past",
        "console": "Super Nintendo",
        "repo": "snesrev/zelda3",
        "scraper": "github_source",
        "source_ref": "v0.3",
        "folder": "Zelda3",
        "has_config": True,
        "type": "Reimpl",
        "platforms": ["macOS", "Linux"],
        "icon_url": None,
        "requires_rom": "zelda3.sfc",
        "rom_checksum": "66871d66be19ad2c34c927d6b14cd8eb6fc3181965b6e517cb361f7316009cfb",
        "requires_asset_extraction": True,
        "assets_marker": "zelda3_assets.dat",
        "build": {
            "brew": ["sdl2"],
            "pip_requirements": "requirements.txt",
            "make_target": "zelda3",      # binary only; ROM needed separately for assets
            "make_jobs": True,
            "make_cflags": "-O2 -Wno-deprecated-non-prototype",  # clang on macOS 15+ is stricter
        },
    },
    {
        "name": "Legend of Dragoon: Severed Chains",
        "game_title": "The Legend of Dragoon",
        "console": "PlayStation",
        "repo": "Legend-of-Dragoon-Modding/Severed-Chains",
        "folder": "SeveredChains",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "Project R",
        "game_title": "San Francisco Rush: The Rock / 2049",
        "console": "Arcade",
        "repo": None,
        "scraper": "t3hd0gg",
        "scraper_url": "https://t3hd0gg.com/project-r/",
        "folder": "ProjectR",
        "type": "Port",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "OpenGOAL Launcher",
        "game_title": "Jak and Daxter: The Precursor Legacy",
        "console": "PlayStation 2",
        "repo": "open-goal/launcher",
        "folder": "JakAndDaxter",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
]
