GAMES = [
    {
        "name": "*** Zelda 64: Recompiled",
        "game_title": "The Legend of Zelda: Majora's Mask",
        "console": "Nintendo 64",
        "repo": "Zelda64Recomp/Zelda64Recomp",
        "folder": "Zelda64Recompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/Zelda64Recomp/Zelda64Recomp/refs/heads/dev/icons/512.png",
        "portable_file": "portable.txt",
        "requires_rom": "mm.n64.us.1.0.z64",
        "rom_checksum_type": "xxh3_64",
        "rom_checksums": ["ef18b4a9e2386169"],  # US 1.0
    },
    {
        "name": "Goemon 64: Recompiled",
        "game_title": "Mystical Ninja Starring Goemon",
        "console": "Nintendo 64",
        "repo": "klorfmorf/Goemon64Recomp",
        "folder": "Goemon64Recompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/klorfmorf/Goemon64Recomp/refs/heads/dev/icons/512.png",
        "portable_file": "portable.txt",
        "requires_rom": "mnsg.us.z64",
        "rom_checksum_type": "xxh3_64",
        "rom_checksums": ["db1bc7ee0e6beba1"],  # US version
    },
    {
        "name": "Mario Kart 64: Recompiled",
        "game_title": "Mario Kart 64",
        "console": "Nintendo 64",
        "repo": "sonicdcer/MarioKart64Recomp",
        "folder": "MarioKart64Recompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/sonicdcer/MarioKart64Recomp/refs/heads/main/icons/512.png",
        "portable_file": "portable.txt",
        "requires_rom": "mk64.us.z64",
        "rom_checksum_type": "xxh3_64",
        "rom_checksums": ["54572403569b87c1"],  # US
    },
    {
        "name": "Duke Nukem: Zero Hour Recompiled",
        "game_title": "Duke Nukem: Zero Hour",
        "console": "Nintendo 64",
        "repo": "sonicdcer/DNZHRecomp",
        "folder": "DNZHRecompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/sonicdcer/DNZHRecomp/refs/heads/main/icons/512.png",
        "portable_file": "portable.txt",
        "requires_rom": "dnzh.us.z64",
        "rom_checksum_type": "xxh3_64",
        "rom_checksums": ["afc33da7101fec88"],  # US
    },
    {
        "name": "Star Fox 64: Recompiled",
        "game_title": "Star Fox 64",
        "console": "Nintendo 64",
        "repo": "sonicdcer/Starfox64Recomp",
        "folder": "Starfox64Recompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/sonicdcer/Starfox64Recomp/refs/heads/main/icons/512.png",
        "portable_file": "portable.txt",
        "requires_rom": "sf64.n64.us.1.1.z64",
        "rom_checksum_type": "xxh3_64",
        "rom_checksums": ["163fd3fc3813f54e"],  # US 1.1 / Rev A
    },
    {
        "name": "Quest 64: Recompiled",
        "game_title": "Quest 64",
        "console": "Nintendo 64",
        "repo": "Rainchus/Quest64-Recomp",
        "folder": "Quest64Recompiled",
        "type": "Recomp",
        "platforms": ["Windows", "Linux"],  # macOS CI builds work, official release coming soon
        "icon_url": None,
        "portable_file": "portable.txt",
    },
    {
        "name": "Smash 64: Recompiled",
        "game_title": "Super Smash Bros.",
        "console": "Nintendo 64",
        "repo": "zestydevy/smash64r",
        "folder": "Smash64Recompiled",
        "type": "Recomp",
        "platforms": ["Windows", "Linux"],  # macOS support in progress
        "icon_url": None,
        "portable_file": "portable.txt",
        "requires_rom": "smashbrothers.us.z64",
        "rom_checksum_type": "xxh3_64",
        "rom_checksums": ["38912ac86097bfec"],  # US
    },
    {
        "name": "Starship",
        "game_title": "Star Fox 64",
        "console": "Nintendo 64",
        "repo": "HarbourMasters/Starship",
        "folder": "Starship",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "Banjo-Kazooie: Recompiled",
        "game_title": "Banjo-Kazooie",
        "console": "Nintendo 64",
        "repo": "BanjoRecomp/BanjoRecomp",
        "folder": "BanjoRecompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/BanjoRecomp/BanjoRecomp/refs/heads/main/icons/app.png",
        "portable_file": "portable.txt",
        "requires_rom": "bk.n64.us.1.0.z64",
        "rom_checksum_type": "xxh3_64",
        "rom_checksums": ["1b67585d56e07f8c"],  # US 1.0
    },
    {
        "name": "Bomberman 64: Recompiled",
        "game_title": "Bomberman 64",
        "console": "Nintendo 64",
        "repo": "RevoSucks/BM64Recomp",
        "folder": "BM64Recompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/RevoSucks/BM64Recomp/refs/heads/master/icons/512.png",
        "portable_file": "portable.txt",
        "requires_rom": "bm64_us.z64",
        "rom_checksum_type": "xxh3_64",
        "rom_checksums": ["c4c0b74bbb696426"],  # US
    },
    {
        "name": "Space Station Silicon Valley: Recompiled",
        "game_title": "Space Station Silicon Valley",
        "console": "Nintendo 64",
        "repo": "Cellenseres/SSSV_Recomp",
        "folder": "SSSVRecompiled",
        "type": "Recomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/Cellenseres/SSSV_Recomp/refs/heads/main/icons/512.png",
        "portable_file": "portable.txt",
        "requires_rom": "sssv.n64.us.1.0.z64",
        "rom_checksum_type": "xxh3_64",
        "rom_checksums": ["912a068aadb0d0c5"],  # US 1.0
    },
    {
        "name": "Ship of Harkinian",
        "game_title": "The Legend of Zelda: Ocarina of Time",
        "console": "Nintendo 64",
        "repo": "harbourmasters/shipwright",
        "folder": "ShipOfHarkinian",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "*** SpaghettiKart",
        "game_title": "Mario Kart 64",
        "console": "Nintendo 64",
        "repo": "harbourmasters/spaghettikart",
        "folder": "SpaghettiKart",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "2 Ship 2 Harkinian",
        "game_title": "The Legend of Zelda: Majora's Mask",
        "console": "Nintendo 64",
        "repo": "harbourmasters/2ship2harkinian",
        "folder": "2Ship2Harkinian",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "Ghost Ship",
        "game_title": "Super Mario 64",
        "console": "Nintendo 64",
        "repo": "harbourmasters/ghostship",
        "folder": "GhostShip",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": "https://raw.githubusercontent.com/HarbourMasters/Ghostship/refs/heads/develop/nx-logo.jpg",
    },
    {
        "name": "Perfect Dark",
        "game_title": "Perfect Dark",
        "console": "Nintendo 64",
        "repo": "fgsfdsfgs/perfect_dark",
        "folder": "PerfectDark",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
        "has_config": True,
        "launch_args": ["--portable"],
        "requires_rom": "pd.ntsc-final.z64",
        "rom_dest_subdir": "data",
        "rom_checksum_type": "md5",
        "rom_checksums": [
            "e03b088b6ac9e0080440efed07c1e40f",  # US V1.1 / ntsc-final (recommended)
            "7f4171b0c8d17815be37913f535e4e93",  # US V1.0 / ntsc-1.0
        ],
    },
    {
        "name": "SM64 Co-op Deluxe",
        "game_title": "Super Mario 64",
        "console": "Nintendo 64",
        "repo": "coop-deluxe/sm64coopdx",
        "folder": "SM64CoopDX",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "Super Mario World",
        "game_title": "Super Mario World",
        "console": "Super Nintendo",
        "repo": "snesrev/smw",
        "scraper": "github_source",
        "source_ref": "main",
        "folder": "SuperMarioWorld",
        "has_config": True,
        "type": "Reimpl",
        "platforms": ["macOS", "Linux"],
        "icon_url": None,
        "requires_rom": "smw.sfc",
        "rom_checksum": "0838e531fe22c077528febe14cb3ff7c492f1f5fa8de354192bdff7137c27f5b",
        "requires_asset_extraction": True,
        "assets_marker": "smw_assets.dat",
        "build": {
            "brew": ["sdl2"],
            "make_target": "smw",
            "make_jobs": True,
            "make_cflags": "-O2 -fno-strict-aliasing",  # strip upstream -Werror
        },
    },
    {
        "name": "Super Metroid",
        "game_title": "Super Metroid",
        "console": "Super Nintendo",
        "repo": "snesrev/sm",
        "scraper": "github_source",
        "source_ref": "main",
        "folder": "SuperMetroid",
        "has_config": True,
        "type": "Reimpl",
        "platforms": ["macOS", "Linux"],
        "icon_url": None,
        "requires_rom": "sm.smc",
        "rom_checksum": "12b77c4bc9c1832cee8881244659065ee1d84c70c3d29e6eaf92e6798cc2ca72",
        "build": {
            "brew": ["sdl2"],
            "make_target": "sm",
            "make_jobs": True,
            "make_cflags": "-O2 -fno-strict-aliasing",  # strip upstream -Werror
        },
    },
    {
        "name": "Zelda: A Link to the Past",
        "game_title": "The Legend of Zelda: A Link to the Past",
        "console": "Super Nintendo",
        "repo": "snesrev/zelda3",
        "scraper": "github_source",
        "source_ref": "v0.3",
        "folder": "Zelda3",
        "has_config": True,
        "type": "Reimpl",
        "platforms": ["macOS", "Linux"],
        "icon_url": None,
        "requires_rom": "zelda3.sfc",
        "rom_checksum": "66871d66be19ad2c34c927d6b14cd8eb6fc3181965b6e517cb361f7316009cfb",
        "requires_asset_extraction": True,
        "assets_marker": "zelda3_assets.dat",
        "build": {
            "brew": ["sdl2"],
            "pip_requirements": "requirements.txt",
            "make_target": "zelda3",      # binary only; ROM needed separately for assets
            "make_jobs": True,
            "make_cflags": "-O2 -Wno-deprecated-non-prototype",  # clang on macOS 15+ is stricter
        },
    },
    {
        "name": "Legend of Dragoon: Severed Chains",
        "game_title": "The Legend of Dragoon",
        "console": "PlayStation",
        "repo": "Legend-of-Dragoon-Modding/Severed-Chains",
        "folder": "SeveredChains",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
        "requires_discs": 4,
        "disc_dest_subdir": "isos",
    },
    {
        "name": "Project R",
        "game_title": "San Francisco Rush: The Rock / 2049",
        "console": "Arcade",
        "repo": None,
        "scraper": "t3hd0gg",
        "scraper_url": "https://t3hd0gg.com/project-r/",
        "folder": "ProjectR",
        "type": "Port",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "OpenGOAL Launcher",
        "game_title": "Jak and Daxter: The Precursor Legacy",
        "console": "PlayStation 2",
        "repo": "open-goal/launcher",
        "folder": "JakAndDaxter",
        "type": "Decomp",
        "platforms": ["macOS", "Windows", "Linux"],
        "icon_url": None,
    },
    {
        "name": "Animal Crossing",
        "game_title": "Animal Crossing",
        "console": "GameCube",
        # Primary repo — use once GL_SILENCE_DEPRECATION appears in pc/CMakeLists.txt
        "repo": "flyngmt/ACGC-PC-Port",
        "scraper": "github_source",
        "source_ref": "main",
        # Until that merge lands, use the working macOS PR fork instead
        "source_ref_pr_fallback": {
            "repo": "birabittoh/ACGC-PC-Port",
            "ref": "master",
            "check_url": "https://raw.githubusercontent.com/flyngmt/ACGC-PC-Port/main/pc/CMakeLists.txt",
            "check_pattern": "GL_SILENCE_DEPRECATION",
        },
        "folder": "AnimalCrossing",
        "type": "Decomp",
        "platforms": ["macOS"],
        "icon_url": None,
        "has_config": True,
        "requires_rom": "animal_crossing.iso",
        "rom_dest_subdir": "pc/build/bin/rom",
        "rom_description": "Animal Crossing (USA, GAFE01) GameCube disc image (.iso / .gcm)",
        "rom_validation_magic": {"offset": 0x1C, "hex": "c2339f3d"},  # GCN disc magic
        "launch_subdir": "pc/build/bin",
        "build": {
            "brew": ["gcc", "ninja", "sdl2"],
            "cmake": True,
            "cmake_source_subdir": "pc",
            "cmake_use_gcc": True,
            "cmake_binary": "ACGCPC",
            "make_jobs": True,
        },
    },

    # ── Game Boy ────────────────────────────────────────────────────────────────

    {
        "name": "Pokemon Red / Blue",
        "game_title": "GB Recompiled",
        "console": "Game Boy",
        "folder": "PokemonRedBlue",
        "type": "Recomp",
        "platforms": ["macOS"],
        "icon_url": None,
        "build_type": "gb_recomp",
        "source_repo": "pret/pokered",
        "gb_variants": [
            {"key": "red",  "stem": "pokered",  "make_target": "",     "label": "RED VERSION",  "source_repo": "pret/pokered"},
            {"key": "blue", "stem": "pokeblue", "make_target": "blue", "label": "BLUE VERSION", "source_repo": "pret/pokered"},
        ],
    },
    {
        "name": "Super Mario Land",
        "game_title": "GB Recompiled",
        "console": "Game Boy",
        "folder": "SuperMarioLand",
        "type": "Recomp",
        "platforms": ["macOS"],
        "icon_url": None,
        "build_type": "gb_recomp",
        "source_repo": "kaspermeerts/supermarioland",
        "gb_variants": [
            {"key": "world", "stem": "mario", "make_target": "", "label": "WORLD VERSION",
             "source_repo": "kaspermeerts/supermarioland", "rom_ext": "gb"},
        ],
    },
    {
        "name": "Metroid II: Return of Samus",
        "game_title": "GB Recompiled",
        "console": "Game Boy",
        "folder": "MetroidII",
        "type": "Recomp",
        "platforms": ["macOS"],
        "icon_url": None,
        "build_type": "gb_recomp",
        "source_repo": "metroidret/M2RoS",
        # Original ROM needed to extract tilesets, maps, and GFX before assembling
        "requires_source_rom": "Metroid2.gb",
        "gb_variants": [
            {"key": "us", "stem": "M2RoS", "make_target": "", "label": "US VERSION",
             "source_repo": "metroidret/M2RoS", "rom_ext": "gb", "rom_src_path": "out/M2RoS.gb",
             # rgbasm -L (disable LD→LDH optimisation) was removed in RGBDS v0.8.0
             "makefile_patches": [{"file": "Makefile", "old": " -L", "new": ""}],
             "pre_make": [["python3", "extract.py"]]},
        ],
    },
    {
        "name": "Final Fantasy Adventure",
        "game_title": "GB Recompiled",
        "console": "Game Boy",
        "folder": "FinalFantasyAdventure",
        "type": "Recomp",
        "platforms": ["macOS"],
        "icon_url": None,
        "build_type": "gb_recomp",
        "source_repo": "daid/FFA-Disassembly",
        "gb_variants": [
            {"key": "us", "stem": "ffa", "make_target": "", "label": "US VERSION",
             "source_repo": "daid/FFA-Disassembly", "rom_ext": "gb", "rom_src_path": "rom.gb"},
        ],
    },
    {
        "name": "Zelda: Link's Awakening DX",
        "game_title": "GB Recompiled",
        "console": "Game Boy",
        "folder": "LinksAwakeningDX",
        "type": "Recomp",
        "platforms": ["macOS"],
        "icon_url": None,
        "build_type": "gb_recomp",
        "source_repo": "zladx/LADX-Disassembly",
        "gb_variants": [
            {"key": "us", "stem": "azle", "make_target": "", "label": "US VERSION", "source_repo": "zladx/LADX-Disassembly"},
        ],
    },
    {
        "name": "Pokemon Gold / Silver / Crystal",
        "game_title": "GB Recompiled",
        "console": "Game Boy",
        "folder": "PokemonGSC",
        "type": "Recomp",
        "platforms": ["macOS"],
        "icon_url": None,
        "build_type": "gb_recomp",
        "source_repo": "pret/pokegold",
        "gb_variants": [
            {"key": "gold",    "stem": "pokegold",    "make_target": "gold",   "label": "GOLD VERSION",    "source_repo": "pret/pokegold"},
            {"key": "silver",  "stem": "pokesilver",  "make_target": "silver", "label": "SILVER VERSION",  "source_repo": "pret/pokegold"},
            {"key": "crystal", "stem": "pokecrystal", "make_target": "",       "label": "CRYSTAL VERSION", "source_repo": "pret/pokecrystal"},
        ],
    },
]
